config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'hash' => 'welcome#hash'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @homeland = 'Puerto Rico'
    @travel_pics = ['budapest.jpg', 'Cambodia.jpg', 'Vietnam.jpg' , 'Thailand.jpg']
  end

  def about
  	@color = params[:color]
  	@size = params[:size]
  end

  def about
    @color = params[:color]
    @size = params[:size].to_i
  end

  def contact
  end

  def hash
   @united_states = {"capital city" => "Washington, DC", 
                     "favorite city" => "Asheville, NC", 
                     "favorite state" => "California", 
                     "flag colors" => ["red", "white", "blue"]}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>

</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Travel", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "About", about_path %> <span class="sr-only">(current)</span></li>
        <li class="active"><%= link_to "Hash", hash_path %> <span class="sr-only">(current)</span></li>
        <li class="active"><%= link_to "Contact", contact_path %> <span class="sr-only">(current)</span></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>







<div class="container">
<%= yield %>
</div>


</body>
</html>

app/views/welcome/about.html.erb
<style>
	body {
		background:<%=@color%>;
	}
	</style>

<h1>About me</h1>
<p>Lots of interesting stuff.</p>
<p>My favorite color is <%= @color %></p>


<% if @size > 12 %>
  <p>My shoe size is <%= @size %>. I have HUGE feet.</p>
<% else %>
  <p>My shoe size is <%= @size %></p>
<% end %>

<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>

<%= link_to "Green", about_path(color: "green"), class: "btn btn-success" %>

<%= link_to "Red", about_path(color: "red"), class: "btn btn-danger" %>

<%= link_to "Orange", about_path(color: "orange"), class: "btn btn-warning" %>

app/views/welcome/contact.html.erb
<h1>Welcome to my Contact page</h1>

app/views/welcome/hash.html.erb
<table class="table">
  <tr>
    <% @united_states.each do |key,value| %>
	  <th><%= key.titleize %></th>
    <% end %>
  </tr>
  <tr>
    <% @united_states.each do |key,value| %>      
      <% if value.kind_of?(Array) %>
          <td><%= value.join(", ") %></td>
      <% else %>
         <td><%= value %></td>
      <% end %> 
    <% end %>
  </tr>
</table>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>This is my very awesome travel site.</p>

<p>My homeland is Earth</p>

Countries I'd like to visit
<ul>
<li>Chile</li>
<li>Brazil</li>
<li>Croatia</li>
</ul>

<% @travel_pics.each do |pic| %>
  <%= image_tag pic, class:"img_responsive"%>
<% end %>